---
abstract: "Exodist's collection of utility functions"
author:
  - 'Chad Granum <exodist7@gmail.com>'
build_requires:
  Test::Exception: 0
  Test::More: 0.88
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Exodist-Util
provides:
  Exodist::Util:
    file: lib/Exodist/Util.pm
    version: 0.005
  Exodist::Util::Accessors:
    file: lib/Exodist/Util/Accessors.pm
  Exodist::Util::Alias:
    file: lib/Exodist/Util/Alias.pm
  Exodist::Util::Loader:
    file: lib/Exodist/Util/Loader.pm
  Exodist::Util::Package:
    file: lib/Exodist/Util/Package.pm
  Exodist::Util::Sub:
    file: lib/Exodist/Util/Sub.pm
requires:
  Devel::BeginLift: 0.001003
  Exporter::Declare: 0.100
  List::Util: 0
  Scalar::Util: 0
  perl: 5.008
resources:
  bugtracker: http://github.com/exodist/Exodist-Util/issues
  homepage: http://open-exodus.net/projects/Exodist-Util
  license: http://dev.perl.org/licenses/
  repository: http://github.com/exodist/Exodist-Util
version: 0.005
